version: 2.1
commands:
 actualizar:
   steps:
      - run: apt-get update && apt-get install -y
      - run: timedatectl set-timezone Europe/Madrid
      - run: apt-get install docker -y es_ES
jobs:
  base:
    docker:
      - image: ubuntu:20.04
    steps:
      - actualizar

workflows:
  proceso:
    jobs:
      - base

